=== Eileen909/Lab_Excercise_5_WSD/Lab_Excercise_5_WSD/carproduct.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="ProductDetails">
    <xs:complexType>
      <xs:sequence>
    
        <xs:element name="Product" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ProductID" type="xs:string"/>
              <xs:element name="Name" type="xs:string"/>
              <xs:element name="Type" type="xs:string"/>
              <xs:element name="Price" type="PriceType"/>
              <xs:element name="ModelNo" type="ModelNoType"/>
              <xs:element name="Colour" type="xs:string"/>
              <xs:element name="Warranty" type="WarrantyType"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="PriceType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0.01"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ModelNoType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="3"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="WarrantyType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Eileen909/Lab_Excercise_5_WSD/Lab_Excercise_5_WSD/carproduct.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProductDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="carproduct.xsd">
                <?xml-stylesheet type="text/xsl" href="transform.xsl"?>

  <Product id="PDT001">
    <ProductID>CGS098</ProductID>
    <Name>Continental GTC Speed</Name>
    <Type>Sports Car</Type>
    <Price>2300000.00</Price>
    <ModelNo>2024</ModelNo>
    <Colour>Shiny Green</Colour>
    <Warranty>5</Warranty>
  </Product>
  <Product id="PDT002">
    <ProductID>BEA876</ProductID>
    <Name>Bentayga EWB Azure</Name>
    <Type>SUV</Type>
    <Price>2506000.00</Price>
    <ModelNo>2023</ModelNo>
    <Colour>Shiny Black</Colour>
    <Warranty>10</Warranty>
  </Product>
  <Product id="PDT003">
    <ProductID>SPX123</ProductID>
    <Name>Flying Spur X</Name>
    <Type>Car</Type>
    <Price>2000800.00</Price>
    <ModelNo>2019</ModelNo>
    <Colour>Navy Blue</Colour>
    <Warranty>3</Warranty>
  </Product>
</ProductDetails>
